[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Colors
[[plugins]]
# repo = 'cocopon/iceberg.vim/'
repo = 'drewtempelmeyer/palenight.vim'
hook_add = '''
  set termguicolors
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  colorscheme palenight
  autocmd ColorScheme * highlight Normal  guibg=None
  autocmd ColorScheme * highlight NonText guibg=None
'''

# airline
[[plugins]]
repo    = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'palenight'
'''

# yank highlight
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 200
'''

# caw
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <Leader>c <Plug>(caw:zeropos:toggle)
  vmap <Leader>c <Plug>(caw:zeropos:toggle)
'''

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <leader>gap :Git add %:p<CR><CR>
  nnoremap <leader>gaa :Git add .<CR><CR>
  nnoremap <leader>gc :Gcommit<CR><CR>
  nnoremap <leader>gs :Gstatus<CR>
  nnoremap <leader>gp :Gpush<CR>
  nnoremap <leader>gd :Gdiff<CR>
  nnoremap <leader>gl :Glog<CR>
  nnoremap <leader>gb :Gblame<CR>
'''

# whitespace
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = '''
  source ~/.config/nvim/coc-setting.vim
'''

# easy motion
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_smartcase = 1
  map  f <Plug>(easymotion-bd-f)
  nmap f <Plug>(easymotion-overwin-f)
  map  <C-w> <Plug>(easymotion-bd-w)
  nmap <C-w> <Plug>(easymotion-overwin-w)
'''


