[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

# previm
[[plugins]]
repo = 'previm/previm'
hook_add = '''
	let g:previm_open_cmd = 'open -a Firefox'
  augroup PrevimSettings
      autocmd!
      autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
  augroup END
'''
on_i = 1

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add= '''
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
  let NERDTreeMinimalUI=1
'''
on_i =1

[[plugins]]
repo = 'Chiel92/vim-autoformat'

hook_add= '''
  nnoremap <C-f> :Autoformat<CR>
'''
on_i =1


