[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    " qでバッファ閉じる
    au FileType qf nnoremap <silent><buffer>q :quit<CR>
    
    " \rで書き込んで実行
    let g:quickrun_no_default_key_mappings = 1
    nnoremap \r :write<CR>:QuickRun -mode n<CR>        
    xnoremap \r :<C-U>write<CR>gv:QuickRun -mode v<CR> 
    let g:quickrun_no_default_key_mappings = 1
    nnoremap \r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
    xnoremap \r :<C-U>cclose<CR>:write<CR>gv:QuickRun -mode v<CR>
    
    " C-cで強制終了
    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
    " latexmk
    let g:quickrun_config = {}
    let g:quickrun_config['tex'] = {
            \   'command' : 'latexmk',
            \   'outputter' : 'error',
            \   'outputter/error/error' : 'quickfix',
            \   'cmdopt': '-pv -pdfdvi',
            \   'exec': ['%c %o %s']
            \ }
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_post_source = ''''
    nmap \c <Plug>(caw:zeropos:toggle)
    vmap \c <Plug>(caw:zeropos:toggle)
'''

# Colors
[[plugins]]
repo = 'lu-ren/SerialExperimentsLain'
