[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Colors
[[plugins]]
# repo = 'cocopon/iceberg.vim/'
repo = 'drewtempelmeyer/palenight.vim'
hook_add = '''
  set termguicolors
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  colorscheme palenight
  autocmd ColorScheme * highlight Normal  guibg=None
  autocmd ColorScheme * highlight NonText guibg=None
'''

# airline
[[plugins]]
repo    = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'palenight'
'''

# yank highlight
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 200
'''

# caw
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <Leader>c <Plug>(caw:zeropos:toggle)
  vmap <Leader>c <Plug>(caw:zeropos:toggle)
'''

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <leader>gap :Git add %:p<CR><CR>
  nnoremap <leader>gaa :Git add .<CR><CR>
  nnoremap <leader>gc :Gcommit<CR><CR>
  nnoremap <leader>gs :Gstatus<CR>
  nnoremap <leader>gp :Gpush<CR>
  nnoremap <leader>gd :Gdiff<CR>
  nnoremap <leader>gl :Glog<CR>
  nnoremap <leader>gb :Gblame<CR>
'''

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_fileTypeExclude = ['md', 'markdown']
'''

# easy motion
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_smartcase = 1
  map  <C-w> <Plug>(easymotion-bd-w)
  nmap <C-w> <Plug>(easymotion-overwin-w)
'''

# d2
[[plugins]]
repo = 'terrastruct/d2-vim'

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = 'fzf#install()'
hook_add = '''
  noremap <C-p> :Files<CR>
  noremap <leader><space> :Command<CR>
'''
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

# treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

# nvim cmp
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
repo = 'github/copilot.vim'
hook_add = '''
'''
