[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Colors
[[plugins]]
repo = 'arcticicestudio/nord-vim'
repo = 'reedes/vim-colors-pencil'
hook_add = '''
  set termguicolors
  set background=dark
  colorscheme pencil
'''

# yank highlight
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 300
'''
# caw
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <Leader>c <Plug>(caw:zeropos:toggle)
  vmap <Leader>c <Plug>(caw:zeropos:toggle)
'''

# whitespace
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'

# Coc
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = '''
  source ~/.config/nvim/coc-setting.vim
'''

# easy motion
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_smartcase = 1
  map  f <Plug>(easymotion-bd-f)
  nmap f <Plug>(easymotion-overwin-f)
  map  W <Plug>(easymotion-bd-w)
  nmap W <Plug>(easymotion-overwin-w)
'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'pencil'
'''

