version: 2
root-markers:
  - .git/

tools:
  textlint: &textlint
    lint-command: 'textlint --format unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%n: %m'
    root-markers:
      - .textlintrc

languages:
  markdown:
    - <<: *textlint
  tex:
    - <<: *textlint
